if (GetLocale() == "ruRU") then
	-- Russian localization by Lichery
    FTAB_LOADED = "FonTabulous загружен! Введите /ftab или /fontabulous, чтобы изменить настройки шрифтов"
    INVALID_FONT = "Выбран некорректный шрифт"
	BUTTON = "Кнопка "
    CURRENT_FONT = "|cffffffffТекущий шрифт: "
	APPLY = "Применить"
	PREVIEW = "Предпросмотр"
	AUTO_RELOADUI = "Автоматическая перезагрузка интерфейса\nпосле изменения шрифта"
	FONT_SCALE = "Размер шрифта (%)"
	NORMAL_TEXT = "Обычный текст / Normal Text"
	BOLD_TEXT = "Полужирный текст / Bold Text"
	ITALIC_TEXT = "Курсивный текст / Italic Text"
	LARGE_MSG_TEXT = "Большой текст сообщения / Large Message Text"
	RELOAD_MSG = "Некоторые элементы не будут отображаться правильно, если вы не перезагрузите Ваш интерфейс, вы хотите сделать это сейчас?"
else
    FTAB_LOADED = "FonTabulous Loaded! Type /ftab or /fontabulous to change your font settings"
    INVALID_FONT = "Invalid Font Selection"
	BUTTON = "Button "
    CURRENT_FONT = "|cffffffffCurrent using: "
	APPLY = "Apply"
	PREVIEW = "Preview"
	AUTO_RELOADUI = "Auto ReloadUI When Changing Fonts"
	FONT_SCALE = "Font Scale (%)"
	NORMAL_TEXT = "Normal Text"
	BOLD_TEXT = "Bold Text"
	ITALIC_TEXT = "Italic Text"
	LARGE_MSG_TEXT = "Large Message Text"
	RELOAD_MSG = "Some elements will not display properly unless you Reload your UI, do you wish to do that now?"
end